import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import javax.swing.JFrame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author karly
 */
public class Login1 extends javax.swing.JDialog implements AutoCloseable, WindowListener{
    private boolean acceso;
    
    enum UI {
        Inicial, IniciarSesion
    }
   
    /**
     * Creates new form Login
     */
    public Login1(JFrame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        // changeUI(UI.Inicial);
        this.addWindowListener(this);
    }

    public Login1() {
        super();
        initComponents();
        // changeUI(UI.Inicial);
        this.addWindowListener(this);
    }

    public void windowClosing(WindowEvent e) {
        close();
    }
    public void windowOpened(WindowEvent e){}
    public void windowActivated(WindowEvent e){}
    public void windowDeactivated(WindowEvent e){}
    public void windowDeiconified(WindowEvent e){}
    public void windowIconified(WindowEvent e){}
    public void windowClosed(WindowEvent e){}

//     private void changeUI(UI interfaz) {
//         Component[] components = { btnIS, btnRegistrarse, btnAceptar, btnCancelar, lblUsuario, lblContraseña, txtUsuario, jpswContraseña};
//         boolean b = interfaz == UI.Inicial;
//         for (int i = 0; i<components.length; i++)
//         {
//             if (i <= 1)
//             {
//                 components[i].setVisible(b);
//             }
//             else {
//                 components[i].setVisible(!b);
//             }
//         }
//     }
    
//     private void validarCampoVacio(JLabel lbl, JTextField tfs) throws RuntimeException {
//         lbl.setForeground(Color.black);
//         if (tfs.getText() == null) {
//             lbl.setForeground(Color.red);
//             tfs.requestFocus();
//             throw new RuntimeException(
//                     tfs.getName().equals("txtUsuario") ? "El CURP está vacío" : "La Contraseña está vacío");
//         }
//     }

//     public void login() {
//         boolean noEncontrado = true;
//         for (int i = 0; i < Principal.alumnos.size(); i++) {
//             if (Principal.alumnos.get(i).getCURP().equalsIgnoreCase(txtUsuario.getText())) {
//                 if (Principal.alumnos.get(i).getContraseña().equals(jpswContraseña.getText())) {
//                     showMessageDialog(this, "Acceso concedido");
//                     acceso = true;
//                     this.close();
//                     return;
//                 } else {
//                     showMessageDialog(this, "No coincide la CURP y la contraseña");
//                     noEncontrado = false;
//                     break;
//                 }
//             }
//         }
//         if (noEncontrado)
//             showMessageDialog(this, "No se encontró al alumno con CURP " + txtUsuario.getText());
//     }

    public void close() {
        Principal.setAcceso(acceso);
        this.dispose();
    }

//     /**
//      * This method is called from within the constructor to initialize the form.
//      * WARNING: Do NOT modify this code. The content of this method is always
//      * regenerated by the Form Editor.
//      */
//     @SuppressWarnings("unchecked")
//     // <editor-fold defaultstate="collapsed" desc="Generated
//     // <editor-fold defaultstate="collapsed" desc="Generated
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setForeground(new java.awt.Color(51, 0, 51));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo becat.png"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel1, new java.awt.GridBagConstraints());

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

//     /**
//      * @param args the command line arguments
//      */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login1().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
    // private ArrayList<Alumno> alumnos = new ArrayList<Alumno>();
    
}
