import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import javax.swing.JFrame;
import java.util.ArrayList;
import javax.swing.JTextField;
import static javax.swing.JOptionPane.*;
import javax.swing.JLabel;
import java.awt.Color;
import java.awt.Component;
import javax.swing.JRootPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author karly
 */
public class Login1 extends javax.swing.JDialog implements AutoCloseable, WindowListener{
    private boolean acceso;
    
    enum UI {
        Inicial, IniciarSesion
    }
   
    /**
     * Creates new form Login
     */
    public Login1(JFrame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        changeUI(UI.Inicial);
        this.addWindowListener(this);
    }

    public Login1() {
        super();
        initComponents();
        changeUI(UI.Inicial);
        this.addWindowListener(this);
    }

    public void windowClosing(WindowEvent e) {
        close();
    }

    public void windowOpened(WindowEvent e){}
    public void windowActivated(WindowEvent e){}
    public void windowDeactivated(WindowEvent e){}
    public void windowDeiconified(WindowEvent e){}
    public void windowIconified(WindowEvent e){}
    public void windowClosed(WindowEvent e){}

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnCancelarActionPerformed
        changeUI(UI.Inicial);
    }// GEN-LAST:event_btnCancelarActionPerformed

    private void changeUI(UI interfaz) {
        for (Component c : this.getContentPane().getComponents()) {
            c.setVisible(false);
        }
        switch (interfaz) {
            case Inicial:
                Component[] c = { btnIS, btnRegistrarse, jLabel1 };
                for (Component cc : c) {
                    cc.setVisible(true);
                }
                break;
            case IniciarSesion:
                Component[] components = { btnAceptar, btnCancelar, jPasswordField1, lblContraseña, lblUsuario,
                        txtUsuario };
                for (Component cc : components) {
                    cc.setVisible(true);
                }
                break;
        }
    }

    private void btnISActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnISActionPerformed
        changeUI(UI.IniciarSesion);
    }// GEN-LAST:event_btnISActionPerformed

    private void btnRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnRegistrarseActionPerformed
        this.setVisible(false);
        Ventana2 abrir = new Ventana2(this, true);
        this.setVisible(true);
    }// GEN-LAST:event_btnRegistrarseActionPerformed

    private void validarCampoVacio(JLabel lbl, JTextField tfs) throws RuntimeException {
        lbl.setForeground(Color.black);
        if (tfs.getText().equals("")) {
            lbl.setForeground(Color.red);
            tfs.requestFocus();
            throw new RuntimeException(
                    tfs.getName().equals("txtUsuario") ? "El CURP está vacío" : "La Contraseña está vacío");
        }
    }

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnAceptarActionPerformed
        try {
            validarCampoVacio(lblUsuario, txtUsuario);
            validarCampoVacio(lblContraseña, jPasswordField1);
        } catch (RuntimeException e) {
            showMessageDialog(this, e.getMessage());
        }
        // pasada de lista de alumnos
        login();
    }// GEN-LAST:event_btnAceptarActionPerformed

    public void login() {
        boolean noEncontrado = true;
        for (int i = 0; i < Principal.alumnos.size(); i++) {
            if (Principal.alumnos.get(i).getCURP().equalsIgnoreCase(txtUsuario.getText())) {
                if (Principal.alumnos.get(i).getContraseña().equals(jPasswordField1.getText())) {
                    showMessageDialog(this, "Acceso concedido");
                    acceso = true;
                    this.close();
                    return;
                } else {
                    showMessageDialog(this, "No coincide la CURP y la contraseña");
                    noEncontrado = false;
                    break;
                }
            }
        }
        if (noEncontrado)
            showMessageDialog(this, "No se encontró al alumno con CURP " + txtUsuario.getText());
    }

    public void close() {
        Principal.setAcceso(acceso);
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setForeground(new java.awt.Color(51, 0, 51));
        setPreferredSize(new java.awt.Dimension(270, 480));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseño sin título.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-190, -10, 720, 860));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 320, 440));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
    // private ArrayList<Alumno> alumnos = new ArrayList<Alumno>();
    
}