/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author karly
 */
public class Ventana41 extends javax.swing.JFrame {

    /**
     * Creates new form Ventana4
     */
    public Ventana41() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        btnRegistrar = new javax.swing.JButton();
        lblSiguiente = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblPromedioAnterior = new javax.swing.JLabel();
        txtPA = new javax.swing.JTextField();
        lblMatricula = new javax.swing.JLabel();
        txtMatricula = new javax.swing.JTextField();
        lblPromedioGeneral = new javax.swing.JLabel();
        txtPG = new javax.swing.JTextField();
        chbxActivo = new javax.swing.JCheckBox();
        chbxRegular = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        lblPeriodo = new javax.swing.JLabel();
        txtPeriodo = new javax.swing.JTextField();
        lblTipoPeriodo = new javax.swing.JLabel();
        cmbTperiodo = new javax.swing.JComboBox<>();
        lblTotalPeriodos = new javax.swing.JLabel();
        txtTPeriodos = new javax.swing.JTextField();
        lblPeriodoActual = new javax.swing.JLabel();
        lblPeriodoActual1 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        lblPeriodoActual2 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegistrar.setBackground(new java.awt.Color(51, 204, 0));
        btnRegistrar.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        btnRegistrar.setText("Registrar");
        getContentPane().add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 500, 150, 50));

        lblSiguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flecha-correcta.png"))); // NOI18N
        lblSiguiente.setToolTipText("Siguiente");
        getContentPane().add(lblSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 560, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Información Escolar del Alumno:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, -1, -1));

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.GridBagLayout());

        lblPromedioAnterior.setBackground(java.awt.Color.lightGray);
        lblPromedioAnterior.setFont(new java.awt.Font("New Gulim", 1, 18)); // NOI18N
        lblPromedioAnterior.setForeground(new java.awt.Color(255, 255, 255));
        lblPromedioAnterior.setText("Promedio Anterior: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 30;
        jPanel1.add(lblPromedioAnterior, gridBagConstraints);

        txtPA.setBackground(java.awt.Color.lightGray);
        txtPA.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanel1.add(txtPA, gridBagConstraints);

        lblMatricula.setBackground(java.awt.Color.lightGray);
        lblMatricula.setFont(new java.awt.Font("New Gulim", 1, 18)); // NOI18N
        lblMatricula.setForeground(new java.awt.Color(255, 255, 255));
        lblMatricula.setText("Matricula:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanel1.add(lblMatricula, gridBagConstraints);

        txtMatricula.setBackground(java.awt.Color.lightGray);
        txtMatricula.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanel1.add(txtMatricula, gridBagConstraints);

        lblPromedioGeneral.setBackground(java.awt.Color.lightGray);
        lblPromedioGeneral.setFont(new java.awt.Font("New Gulim", 1, 18)); // NOI18N
        lblPromedioGeneral.setForeground(new java.awt.Color(255, 255, 255));
        lblPromedioGeneral.setText("Promedio General:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanel1.add(lblPromedioGeneral, gridBagConstraints);

        txtPG.setBackground(java.awt.Color.lightGray);
        txtPG.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanel1.add(txtPG, gridBagConstraints);

        chbxActivo.setFont(txtMatricula.getFont());
        chbxActivo.setForeground(new java.awt.Color(255, 255, 255));
        chbxActivo.setText("Estudiante Activo");
        chbxActivo.setOpaque(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanel1.add(chbxActivo, gridBagConstraints);

        chbxRegular.setFont(txtMatricula.getFont());
        chbxRegular.setForeground(new java.awt.Color(255, 255, 255));
        chbxRegular.setText("Estudiante Regular");
        chbxRegular.setOpaque(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanel1.add(chbxRegular, gridBagConstraints);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 180, 210, 310));

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.GridBagLayout());

        lblPeriodo.setBackground(java.awt.Color.lightGray);
        lblPeriodo.setFont(new java.awt.Font("New Gulim", 1, 18)); // NOI18N
        lblPeriodo.setForeground(new java.awt.Color(255, 255, 255));
        lblPeriodo.setText("Periodo:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel2.add(lblPeriodo, gridBagConstraints);

        txtPeriodo.setBackground(java.awt.Color.lightGray);
        txtPeriodo.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanel2.add(txtPeriodo, gridBagConstraints);

        lblTipoPeriodo.setBackground(java.awt.Color.lightGray);
        lblTipoPeriodo.setFont(new java.awt.Font("New Gulim", 1, 18)); // NOI18N
        lblTipoPeriodo.setForeground(new java.awt.Color(255, 255, 255));
        lblTipoPeriodo.setText("Tipo Periodo:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanel2.add(lblTipoPeriodo, gridBagConstraints);

        cmbTperiodo.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanel2.add(cmbTperiodo, gridBagConstraints);

        lblTotalPeriodos.setBackground(java.awt.Color.lightGray);
        lblTotalPeriodos.setFont(new java.awt.Font("New Gulim", 1, 18)); // NOI18N
        lblTotalPeriodos.setForeground(new java.awt.Color(255, 255, 255));
        lblTotalPeriodos.setText("Total de Periodos:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanel2.add(lblTotalPeriodos, gridBagConstraints);

        txtTPeriodos.setBackground(java.awt.Color.lightGray);
        txtTPeriodos.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanel2.add(txtTPeriodos, gridBagConstraints);

        lblPeriodoActual.setBackground(java.awt.Color.lightGray);
        lblPeriodoActual.setFont(new java.awt.Font("New Gulim", 1, 18)); // NOI18N
        lblPeriodoActual.setForeground(new java.awt.Color(255, 255, 255));
        lblPeriodoActual.setText("Periodo Actual:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanel2.add(lblPeriodoActual, gridBagConstraints);

        lblPeriodoActual1.setBackground(java.awt.Color.lightGray);
        lblPeriodoActual1.setFont(new java.awt.Font("New Gulim", 1, 18)); // NOI18N
        lblPeriodoActual1.setForeground(new java.awt.Color(255, 255, 255));
        lblPeriodoActual1.setText("Fecha de inicio:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanel2.add(lblPeriodoActual1, gridBagConstraints);

        jDateChooser1.setFont(txtMatricula.getFont());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanel2.add(jDateChooser1, gridBagConstraints);

        lblPeriodoActual2.setBackground(java.awt.Color.lightGray);
        lblPeriodoActual2.setFont(new java.awt.Font("New Gulim", 1, 18)); // NOI18N
        lblPeriodoActual2.setForeground(new java.awt.Color(255, 255, 255));
        lblPeriodoActual2.setText("Fecha de cierre:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanel2.add(lblPeriodoActual2, gridBagConstraints);

        jDateChooser2.setFont(txtMatricula.getFont());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanel2.add(jDateChooser2, gridBagConstraints);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 210, 390));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/123.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1270, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

        private void guardarInfoAlumnos() throws Exception {
        java.io.BufferedWriter bw = null;
        try {
            bw = new java.io.BufferedWriter(new java.io.FileWriter(FILE_NAME));
        } catch (IOException e) {
        }
        String InfoAlumno = "";
        InfoAlumno.add(new InformacionEscolartxtPA.getText().toUpperCase(),txtEstado.getText().toUpperCase());
        for (ClaveInterbancaria a : ClaveInterbancaria) {
             ClabeInterbancariaTxt+= a.getClabe() + "|" + a.getFechaRegistro() + "|" + a.getNombreBanco()+"\n";
        }
        bw.write(ClabeInterbancariatxt);
        bw.flush();
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JCheckBox chbxActivo;
    private javax.swing.JCheckBox chbxRegular;
    private javax.swing.JComboBox<String> cmbTperiodo;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblMatricula;
    private javax.swing.JLabel lblPeriodo;
    private javax.swing.JLabel lblPeriodoActual;
    private javax.swing.JLabel lblPeriodoActual1;
    private javax.swing.JLabel lblPeriodoActual2;
    private javax.swing.JLabel lblPromedioAnterior;
    private javax.swing.JLabel lblPromedioGeneral;
    private javax.swing.JLabel lblSiguiente;
    private javax.swing.JLabel lblTipoPeriodo;
    private javax.swing.JLabel lblTotalPeriodos;
    private javax.swing.JTextField txtMatricula;
    private javax.swing.JTextField txtPA;
    private javax.swing.JTextField txtPG;
    private javax.swing.JTextField txtPeriodo;
    private javax.swing.JTextField txtTPeriodos;
    // End of variables declaration//GEN-END:variables
    public static java.util.ArrayList<InformacionEscolar> infoEscolarAlumno = new java.util.ArrayList<InformacionEscolar>();
    public final static String FILE_NAME = "INFO_ALUMNOS.TXT";
}
