
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.Timer;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author karly
 */
public class VentanaPago extends javax.swing.JFrame {
       private Timer t;
    private final ActionListener ac;
    int x =0;
  
    
    public VentanaPago() {
        initComponents();
        panelPago.setVisible(false);
        this.setLocationRelativeTo(null);
        ac=new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent ae) {
                 x=x+1;
                carga.setValue(x);
                if(carga.getValue()==30){
                     carga.setVisible(false); t.stop();
                       panelPago.setVisible(true);
                }
            }
           
            
        };
        t=new Timer(100,ac);
        t.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        carga = new javax.swing.JProgressBar();
        panelPago = new javax.swing.JPanel();
        lblFechaPago = new javax.swing.JLabel();
        lblTipoPago = new javax.swing.JLabel();
        txtFechaPago = new javax.swing.JTextField();
        txtMonto = new javax.swing.JTextField();
        txtTipoPago = new javax.swing.JTextField();
        lblMonto2 = new javax.swing.JLabel();
        cmbPrograma = new javax.swing.JComboBox<>();
        lblMonto = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel8.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 52)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Pago");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(540, 120, 140, 60);

        carga.setForeground(new java.awt.Color(0, 51, 255));
        carga.setMaximum(375);
        carga.setToolTipText("Selecciona un programa");
        getContentPane().add(carga);
        carga.setBounds(470, 190, 254, 37);

        panelPago.setBackground(new java.awt.Color(0, 51, 51));
        panelPago.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFechaPago.setBackground(java.awt.Color.lightGray);
        lblFechaPago.setFont(new java.awt.Font("Sitka Small", 1, 30)); // NOI18N
        lblFechaPago.setForeground(new java.awt.Color(255, 255, 255));
        lblFechaPago.setText("Fecha de pago: ");
        panelPago.add(lblFechaPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, 30));

        lblTipoPago.setBackground(java.awt.Color.lightGray);
        lblTipoPago.setFont(new java.awt.Font("Sitka Small", 1, 30)); // NOI18N
        lblTipoPago.setForeground(new java.awt.Color(255, 255, 255));
        lblTipoPago.setText("Tipo de pago:");
        panelPago.add(lblTipoPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 270, 30));

        txtFechaPago.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 20)); // NOI18N
        panelPago.add(txtFechaPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 180, 30));

        txtMonto.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 20)); // NOI18N
        panelPago.add(txtMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 180, 30));

        txtTipoPago.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 20)); // NOI18N
        panelPago.add(txtTipoPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 180, 30));

        lblMonto2.setBackground(java.awt.Color.lightGray);
        lblMonto2.setFont(new java.awt.Font("Sitka Small", 1, 30)); // NOI18N
        lblMonto2.setForeground(new java.awt.Color(255, 255, 255));
        lblMonto2.setText("Monto:");
        panelPago.add(lblMonto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 120, 30));

        cmbPrograma.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 20)); // NOI18N
        cmbPrograma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "*Seleccionar*", "Jovenes Pioneros", "Excelencia", "Tlautli" }));
        cmbPrograma.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cmbPrograma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbProgramaActionPerformed(evt);
            }
        });
        panelPago.add(cmbPrograma, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 200, 40));

        lblMonto.setBackground(java.awt.Color.lightGray);
        lblMonto.setFont(new java.awt.Font("Sitka Small", 1, 24)); // NOI18N
        lblMonto.setForeground(new java.awt.Color(255, 255, 255));
        lblMonto.setText("Selecciona un programa");
        panelPago.add(lblMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 400, 30));

        getContentPane().add(panelPago);
        panelPago.setBounds(360, 240, 520, 280);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos de pago.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-10, -30, 1242, 718);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbProgramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProgramaActionPerformed
        if(cmbPrograma.getSelectedIndex()==0){
            showMessageDialog(this,"Por favor selecciona un programa"); return;
        }else if(cmbPrograma.getSelectedIndex()==1){
            txtMonto.setText("$15,000");
            txtFechaPago.setText("20-Agosto-2021");
            txtTipoPago.setText("Deposito");
        }else if(cmbPrograma.getSelectedIndex()==2){
            txtMonto.setText("$20,000");
            txtFechaPago.setText("14-Septiembre-2021");
            txtTipoPago.setText("Deposito");
        }else if(cmbPrograma.getSelectedIndex()==3){
            txtMonto.setText("$18,000");
            txtFechaPago.setText("02-Julio-2021");
            txtTipoPago.setText("Efectivo");
        }
    }//GEN-LAST:event_cmbProgramaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPago().setVisible(true);
            }
        });
    }
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar carga;
    private javax.swing.JComboBox<String> cmbPrograma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblFechaPago;
    private javax.swing.JLabel lblMonto;
    private javax.swing.JLabel lblMonto2;
    private javax.swing.JLabel lblTipoPago;
    private javax.swing.JPanel panelPago;
    private javax.swing.JTextField txtFechaPago;
    private javax.swing.JTextField txtMonto;
    private javax.swing.JTextField txtTipoPago;
    // End of variables declaration//GEN-END:variables
}
