/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author karly
 */
public class Ventana3 extends javax.swing.JFrame {

    /**
     * Creates new form Ventana3
     */
    public Ventana3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCLABE = new javax.swing.JTextField();
        txtEstatus = new javax.swing.JTextField();
        txtBanco = new javax.swing.JTextField();
        txtFechaRegistro = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        lblSiguiente = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        txtCLABE.setBackground(java.awt.Color.lightGray);
        txtCLABE.setFont(new java.awt.Font("NSimSun", 2, 13)); // NOI18N
        getContentPane().add(txtCLABE);
        txtCLABE.setBounds(410, 290, 210, 30);

        txtEstatus.setBackground(java.awt.Color.lightGray);
        txtEstatus.setFont(new java.awt.Font("NSimSun", 2, 18)); // NOI18N
        getContentPane().add(txtEstatus);
        txtEstatus.setBounds(410, 390, 210, 27);

        txtBanco.setBackground(java.awt.Color.lightGray);
        txtBanco.setFont(new java.awt.Font("NSimSun", 2, 13)); // NOI18N
        getContentPane().add(txtBanco);
        txtBanco.setBounds(410, 450, 120, 30);

        txtFechaRegistro.setBackground(java.awt.Color.lightGray);
        txtFechaRegistro.setFont(new java.awt.Font("NSimSun", 2, 18)); // NOI18N
        getContentPane().add(txtFechaRegistro);
        txtFechaRegistro.setBounds(410, 340, 110, 27);

        jLabel4.setBackground(java.awt.Color.lightGray);
        jLabel4.setFont(new java.awt.Font("New Gulim", 1, 18)); // NOI18N
        jLabel4.setText("CLABE");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(330, 290, 60, 21);

        jLabel5.setBackground(java.awt.Color.lightGray);
        jLabel5.setFont(new java.awt.Font("New Gulim", 1, 18)); // NOI18N
        jLabel5.setText("Fecha de Registro");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(230, 330, 164, 21);

        jLabel6.setBackground(java.awt.Color.lightGray);
        jLabel6.setFont(new java.awt.Font("New Gulim", 1, 18)); // NOI18N
        jLabel6.setText("Estatus");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(320, 390, 68, 21);

        jLabel7.setBackground(java.awt.Color.lightGray);
        jLabel7.setFont(new java.awt.Font("New Gulim", 1, 18)); // NOI18N
        jLabel7.setText("Banco");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(340, 450, 57, 21);

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 48)); // NOI18N
        jLabel2.setText("CLABE Interbancaria ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(290, 70, 502, 90);

        btnRegistrar.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        btnRegistrar.setText("Registrar");
        getContentPane().add(btnRegistrar);
        btnRegistrar.setBounds(390, 530, 150, 60);

        lblSiguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flecha-correcta.png"))); // NOI18N
        lblSiguiente.setToolTipText("Siguiente");
        getContentPane().add(lblSiguiente);
        lblSiguiente.setBounds(580, 530, 64, 64);

        jLabel15.setIcon(new javax.swing.ImageIcon("C:\\Users\\karly\\Downloads\\WhatsApp Image 2021-05-26 at 7.28.20 PM.jpeg")); // NOI18N
        getContentPane().add(jLabel15);
        jLabel15.setBounds(-120, -40, 1150, 730);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblSiguiente;
    private javax.swing.JTextField txtBanco;
    private javax.swing.JTextField txtCLABE;
    private javax.swing.JTextField txtEstatus;
    private javax.swing.JTextField txtFechaRegistro;
    // End of variables declaration//GEN-END:variables
}
